version: "3.8"
services:
  database:
    container_name: database
    build: ./db
    environment:
       POSTGRES_USER: postgresadmin
       POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
    restart: always


  api-service:
    container_name: api-service
    build: ./api
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgresadmin:admin123@database:5432/postgres
      SQLALCHEMY_TRACK_MODIFICATIONS: 'false'
    ports:
      - "5000:4000"
    depends_on:
      - database

