version: "3.8"
services:
  urls:
    container_name: urls
    build: ./db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart: always


  api-service:
    container_name: api-service
    build: ./api
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@urls:${DATABASE_PORT}/${DATABASE_NAME}
      SQLALCHEMY_TRACK_MODIFICATIONS: 'false'
      API_PORT: ${API_PORT}
      API_DEBUG: ${API_DEBUG}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - urls
