GRANT ALL PRIVILEGES ON DATABASE postgres TO postgresadmin;
CREATE TABLE URL_MAPPER
(
  URL_ID INT NOT NULL UNIQUE,
  SHORT_URL_ID VARCHAR(20) NOT NULL,
  SHORT_BASE_URL VARCHAR(200) NOT NULL,
  FULL_URL VARCHAR(1000) NOT NULL,
  PRIMARY KEY (URL_ID)
);
