version: "3.8"
services:
  db:
    container_name: db
    image: vishwamitra01/url-shortener-db:latest 
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATABASE: ${DATABASE_NAME}
      PGUSER: ${DATABASE_USER}
      PGPASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --timeout=5"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - urlshortner-data:/var/lib/postgresql/data


  authenticator-service:
    container_name: authenticator-service
    image: vishwamitra01/url-shortener-authenticator:latest
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
      SQLALCHEMY_TRACK_MODIFICATIONS: 'false'
      AUTHENTICATOR_PORT: ${AUTHENTICATOR_PORT}
      AUTHENTICATOR_DEBUG: ${AUTHENTICATOR_DEBUG}
      ACCESS_TOKEN_LIFESPAN: ${ACCESS_TOKEN_LIFESPAN}
    depends_on:
      db:
        condition: service_healthy
  
  api-service:
    container_name: api-service
    image: vishwamitra01/url-shortener-api:latest
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}
      SQLALCHEMY_TRACK_MODIFICATIONS: 'false'
      API_PORT: ${API_PORT}
      API_DEBUG: ${API_DEBUG}
      AUTHENTICATOR_PORT: ${AUTHENTICATOR_PORT}
      AUTHENTICATOR_ENDPOINT: ${AUTHENTICATOR_ENDPOINT}
      BASE_URL_FOR_SHORT_URL: ${BASE_URL_FOR_SHORT_URL}
    depends_on:
      db:
        condition: service_healthy

  proxy:
    container_name: proxy
    image: vishwamitra01/url-shortener-proxy:latest
    environment:
      PROXY_SERVER_NAME: ${PROXY_SERVER_NAME}
      API_PORT: ${API_PORT}
      AUTHENTICATOR_PORT: ${AUTHENTICATOR_PORT}
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    restart: always

volumes:
  urlshortner-data: