name: Docker Image CI

on:
  push:
    tags:        
      - '*' 
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  RELEASE_VERSION: ${GITHUB_REF#refs/*/}

jobs:

#   get-tag:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set env
#         run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
#       - name: Test
#         run: |
#           echo $RELEASE_VERSION
#           echo ${{ env.RELEASE_VERSION }}
      
        
    
  
  build-api:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: url-shortener/api
    steps:
      - uses: actions/checkout@v3
      - name: Docker Image for API
        run: docker build . --file Dockerfile --tag $DOCKER_USER/url-shortener-api:${RELEASE_VERSION}
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push image
        run: docker push --all-tags $DOCKER_USER/url-shortener-api


  build-authenticator:
    runs-on: ubuntu-latest
#     needs: get-tag
    defaults:
      run:
        working-directory: url-shortener/authenticator
    steps:
      - uses: actions/checkout@v3
      - name: Docker image for authenticator
        run: docker build . --file Dockerfile --tag $DOCKER_USER/url-shortener-authenticator:${RELEASE_VERSION}
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push image
        run: docker push --all-tags $DOCKER_USER/url-shortener-authenticator



  build-db:
    runs-on: ubuntu-latest
#     needs: get-tag
    defaults:
      run:
        working-directory: url-shortener/db

    steps:
      - uses: actions/checkout@v3
      - name: Docker image for DB
        run: docker build . --file Dockerfile --tag $DOCKER_USER/url-shortener-db:${RELEASE_VERSION}
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push image
        run: docker push --all-tags $DOCKER_USER/url-shortener-db
