name: Docker Image CI

on:
  push:
    tags:        
      - '*' 
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:

  get-tag:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.SetEnv.outputs.RELEASE_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - id: SetEnv
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> "$GITHUB_OUTPUT"
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      
        
    
  
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: url-shortener/api
    needs: get-tag
    steps:
      - env:
          RELEASE_VERSION: ${{needs.get-tag.outputs.RELEASE_VERSION}}
        run: echo $RELEASE_VERSION
      - uses: actions/checkout@v3
      - name: Docker Image for API
        run: docker build . --file Dockerfile --tag $DOCKER_USER/url-shortener-api:"${{ env.RELEASE_VERSION }}"
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push image
        run: docker push --all-tags $DOCKER_USER/url-shortener-api


  build-authenticator:
    runs-on: ubuntu-latest
#     needs: get-tag
    defaults:
      run:
        working-directory: url-shortener/authenticator
    steps:
      - uses: actions/checkout@v3
      - name: Docker image for authenticator
        run: docker build . --file Dockerfile --tag $DOCKER_USER/url-shortener-authenticator:${RELEASE_VERSION}
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push image
        run: docker push --all-tags $DOCKER_USER/url-shortener-authenticator



  build-db:
    runs-on: ubuntu-latest
#     needs: get-tag
    defaults:
      run:
        working-directory: url-shortener/db

    steps:
      - uses: actions/checkout@v3
      - name: Docker image for DB
        run: docker build . --file Dockerfile --tag $DOCKER_USER/url-shortener-db:${RELEASE_VERSION}
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push image
        run: docker push --all-tags $DOCKER_USER/url-shortener-db
